### ISSUE TITLE
Customizer toggles not hiding

### ISSUE THREAD

**Issue by fastlinemedia** [thethemefoundry/make#277] opened 2015-08-19 17:26 UTC
As of the 4.3 update, controls that should be hidden in the Customizer when another control is toggled are not hiding. We'll they do, but when the preview is refreshed, they are shown again. 

For example, under Layout > Header > Header Layout, when I toggle that control and set it to Centered, the Show Title/Logo On control is hidden but is shown again when the preview refreshes.

This appears to be happening with all controls that should be toggling another control.

**Comment by coreymckrill** [comment] 2015-08-19 20:11
Confirmed. Thanks for the bug report, @fastlinemedia. I'll take a look at this.

**Comment by fastlinemedia** [comment] 2015-08-19 20:13
Thanks, @coreymckrill!

**Comment by coreymckrill** [comment] 2015-08-19 20:24
@fastlinemedia I'm seeing this same issue with core controls in the Customizer as well, with the default Twenty Fifteen theme also. If you go to the "Static Front Page" section and toggle between "Your latest posts" and "A static page", do the two dropdowns exhibit the same behavior for you?

**Comment by fastlinemedia** [comment] 2015-08-19 20:36
Yep, I'm seeing that with Twenty Fifteen as well. Sounds like a core bug then?

**Comment by coreymckrill** [comment] 2015-08-19 20:38
So it would appear. I'll check and see if anyone has reported it yet.

**Comment by fastlinemedia** [comment] 2015-08-19 20:38
Cool. Let me know if there is anything I can do to help!

**Comment by coreymckrill** [comment] 2015-08-19 21:00
Yep, looks like it's been reported: https://core.trac.wordpress.org/ticket/33428

Hopefully a fix will make it into 4.3.1, and then we'll copy it over to the Make code.

**Comment by fastlinemedia** [comment] 2015-08-19 21:23
Great! Thanks for looking into this.

**Comment by coreymckrill** [comment] 2015-09-21 23:39
@fastlinemedia I believe this issue was fixed in version 4.3.1 of WordPress. Can you confirm?

**Closed** 2015-10-01 19:18 UTC
Labels: bug
